### ISSUE TITLE
Lots of failing tests

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/puppet-flapjack#9]
First up, I've not tried running the tests that have been contributed. I'm sure I'm running them correctly. 

I have added a Gemfile, replaced Modulefile with metadata.json, a .ruby_version and run like so:

```
export PUPPET_GEM_VERSION=3.8.2
bundle exec rake spec
```

`271 examples, 113 failures`

The full output is at https://gist.github.com/e07941ada20b64497b88

Eg:

```
Failures:

  1) flapjack::install input validation when the version parameter is not a string should fail
     Failure/Error: expect { subject }.to raise_error(Puppet::Error, /false is not a string./)
       expected Puppet::Error with message matching /false is not a string./ but nothing was raised
     # ./spec/classes/flapjack_install_spec.rb:67:in `block (5 levels) in <top (required)>'

  2) flapjack::redis input validation when the redis_omnibus parameter is not an boolean should fail
     Failure/Error: expect { subject }.to raise_error(Puppet::Error, /"BOGON" is not a boolean.  It looks to be a String/)
       expected Puppet::Error with message matching /"BOGON" is not a boolean.  It looks to be a String/ but nothing was raised
     # ./spec/classes/flapjack_redis_spec.rb:30:in `block (5 levels) in <top (required)>'

  3) flapjack::redis input validation when the redis_port parameter is not a string should fail
     Failure/Error: expect { subject }.to raise_error(Puppet::Error, /false is not a string./)
       expected Puppet::Error with message matching /false is not a string./ but nothing was raised
     # ./spec/classes/flapjack_redis_spec.rb:69:in `block (5 levels) in <top (required)>'

```

**Comment by jessereynolds** [comment]
The repo state when the above tests were run is in the docs_and_tests branch: https://github.com/flapjack/puppet-flapjack/tree/4cfe1ac2df57396b94fd7af965c820e71798500e

**Comment by jessereynolds** [comment]
I'll go ahead and remove the validation tests that are failing as I don't think they're adding much value. Then reassess what tests would be good to have.

**Comment by jessereynolds** [comment]
Largely sorted out in #11
